spring.application.name=webelgremio

# 1. Dirección de tu base de datos MySQL (gremio_db será el nombre de la base de datos)
spring.datasource.url=jdbc:mysql://localhost:3306/gremio_db?createDatabaseIfNotExist=true&serverTimezone=UTC
# 2. Tu usuario de MySQL (por defecto casi siempre es root)
spring.datasource.username=root
# 3. La contraseña que elegiste al instalar MySQL / Workbench
spring.datasource.password=root12345

# 4. Magia: Hibernate creará o actualizará las tablas automáticamente basándose en tus @Entity de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true